// Anti Copy
shortcut={all_shortcuts:{},add:function(a,b,c){var d={type:"keydown",propagate:!1,disable_in_input:!1,target:document,keycode:!1};if(c)for(var e in d)"undefined"==typeof c[e]&&(c[e]=d[e]);else c=d;d=c.target,"string"==typeof c.target&&(d=document.getElementById(c.target)),a=a.toLowerCase(),e=function(d){d=d||window.event;if(c.disable_in_input){var e;d.target?e=d.target:d.srcElement&&(e=d.srcElement),3==e.nodeType&&(e=e.parentNode);if("INPUT"==e.tagName||"TEXTAREA"==e.tagName)return}d.keyCode?code=d.keyCode:d.which&&(code=d.which),e=String.fromCharCode(code).toLowerCase(),188==code&&(e=","),190==code&&(e=".");var f=a.split("+"),g=0,h={"`":"~",1:"!",2:"@",3:"#",4:"$",5:"%",6:"^",7:"&",8:"*",9:"(",0:")","-":"_","=":"+",";":":","'":'"',",":"<",".":">","/":"?","\\":"|"},i={esc:27,escape:27,tab:9,space:32,"return":13,enter:13,backspace:8,scrolllock:145,scroll_lock:145,scroll:145,capslock:20,caps_lock:20,caps:20,numlock:144,num_lock:144,num:144,pause:19,"break":19,insert:45,home:36,"delete":46,end:35,pageup:33,page_up:33,pu:33,pagedown:34,page_down:34,pd:34,left:37,up:38,right:39,down:40,f1:112,f2:113,f3:114,f4:115,f5:116,f6:117,f7:118,f8:119,f9:120,f10:121,f11:122,f12:123},j=!1,l=!1,m=!1,n=!1,o=!1,p=!1,q=!1,r=!1;d.ctrlKey&&(n=!0),d.shiftKey&&(l=!0),d.altKey&&(p=!0),d.metaKey&&(r=!0);for(var s=0;k=f[s],s<f.length;s++)"ctrl"==k||"control"==k?(g++,m=!0):"shift"==k?(g++,j=!0):"alt"==k?(g++,o=!0):"meta"==k?(g++,q=!0):1<k.length?i[k]==code&&g++:c.keycode?c.keycode==code&&g++:e==k?g++:h[e]&&d.shiftKey&&(e=h[e],e==k&&g++);if(g==f.length&&n==m&&l==j&&p==o&&r==q&&(b(d),!c.propagate))return d.cancelBubble=!0,d.returnValue=!1,d.stopPropagation&&(d.stopPropagation(),d.preventDefault()),!1},this.all_shortcuts[a]={callback:e,target:d,event:c.type},d.addEventListener?d.addEventListener(c.type,e,!1):d.attachEvent?d.attachEvent("on"+c.type,e):d["on"+c.type]=e},remove:function(a){var a=a.toLowerCase(),b=this.all_shortcuts[a];delete this.all_shortcuts[a];if(b){var a=b.event,c=b.target,b=b.callback;c.detachEvent?c.detachEvent("on"+a,b):c.removeEventListener?c.removeEventListener(a,b,!1):c["on"+a]=!1}}},shortcut.add("Ctrl+U",function(){top.location.href="https://www.fahmicog.site"});
// Recent Comments Disqus
$(function(){$(".notif-show").on("click",function(){$("#disqus-notif").addClass("active").focus()});$(".close-1").on("click",function(){$("#disqus-notif").removeClass("active")})});$(function(){$(".notif-show").on("click",function(){$("#overlay-1").addClass("active").focus()});$(".close-1").on("click",function(){$("#overlay-1").removeClass("active")})});$("#RecentComments a").filter(function(){return this.hostname&&this.hostname!==location.hostname}).attr('rel', 'nofollow noopener').attr('target', '_blank');
// New updates
function updatedPosts(t){if(document.getElementById("posts-updated")){for(var e,a=t.feed.entry,n="",s=document.getElementById("posts-updated"),r=0;r<7;r++){for(var d=0;d<7;d++)if("alternate"==a[r].link[d].rel){e=a[r].link[d].href;break}var i=a[r].title.$t,l=a[r].published.$t.substring(0,10).replace(/-/g,"/");"media$thumbnail"in a[r]?a[r].media$thumbnail.url:"",n+='<li class="updated">',n+='<strong><a href="'+e+'" target="_blank">'+i+'</a></strong><span class="tanggalnya"> Published on '+l+"</span></li>"}s.innerHTML=n}}function getScript(t){var e=document.createElement("script");e.type="text/javascript",e.src=t,document.body.appendChild(e)}getScript("/feeds/posts/summary?alt=json-in-script&orderby=updated&max-results=7&callback=updatedPosts");
// Notification trigger
var main=function(){$(".notification").click(function(){$(".notification-menu").toggle()})};$(document).ready(main);
// Notif
var _0xfbb9=[".notification-popup",".notification-popup-close","click","shift","push","0x0","fadeOut","0x1","on","0x2"],_0x177c=[_0xfbb9[0],_0xfbb9[1],_0xfbb9[2]];!function(b,c){!function(c){for(;--c;)b[_0xfbb9[4]](b[_0xfbb9[3]]())}(++c)}(_0x177c,407);var _0xcdc7=function(b,c){return _0x177c[b-=0]};$(function(){$(_0xcdc7(_0xfbb9[9]))[_0xfbb9[8]](_0xcdc7(_0xfbb9[5]),function(){$(_0xcdc7(_0xfbb9[7]))[_0xfbb9[6]](170)})});
// Load Comment
function load_Comments(){var e=document.getElementById("disqusshow");e.style.display="none";var t="template-7";!function(){var e=document.createElement("script");e.type="text/javascript",e.async=!0,e.src="https://"+t+".disqus.com/embed.js",(document.getElementsByTagName("head")[0]||document.getElementsByTagName("body")[0]).appendChild(e)}()}
